import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { resolve } from "node:path";
import type { SomaAdapter, Projection, ProjectionInput, SomaTask } from "../../types";
import { activeIsaBundleFile } from "../../adapter-active-isa";
import { rewriteSubstrateProjectionContent } from "../../substrate-projection-rewrites";
import {
  renderAlgorithmRenderingContract,
  renderAssistantCore,
  renderMemoryLayout,
  renderPolicyProjection,
  renderSkills,
  renderSubstrateInstructions,
} from "../shared";

/**
 * Resolve the user-level Grok home (`~/.grok`). `detect()` probes this
 * directory's existence: unlike Codex (`CODEX_HOME`) or Cursor
 * (`CURSOR_TRACE_ID`), Grok exposes no reliable marker env var, so the
 * installed `~/.grok/` tree is the signal. The `homeDir` override keeps
 * `detect()` testable against a temporary home.
 */
export function grokHomeDir(homeDir?: string): string {
  return resolve(homeDir ?? homedir(), ".grok");
}

function renderInstructions(input: ProjectionInput): string {
  return renderSubstrateInstructions({ substrate: "Grok", runtimeLabel: "the Grok CLI" }, input);
}

function renderGrokPolicy(): string {
  return renderPolicyProjection(
    "grok",
    ["Filesystem and tool-call policy when Grok hooks enforce it"],
    [
      "Assistant behavior instructions",
      "Verification reporting",
      "Private context handling",
    ],
  );
}

/**
 * Entry skill for the home projection. `~/.grok/skills/<name>/SKILL.md` is
 * one of the two verified auto-loaded home surfaces (KTD-4a), so this
 * file carries the discovery frontmatter plus the use rules; the bulk
 * context lives in the colocated companion files it points at.
 */
function renderGrokHomeSkill(input: ProjectionInput, somaHome: string): string {
  return [
    "---",
    "name: soma",
    "description: Use when work depends on portable personal assistant context, Soma identity, telos, ISA criteria, memory layout, skills, policy, or default assistant behavior across substrates.",
    "metadata:",
    "  short-description: Portable personal assistant context",
    "---",
    "",
    "# Soma",
    "",
    "Soma is the portable personal assistant core. It keeps assistant identity, principal context, telos, memory, skills, policy, and ISA semantics outside any one substrate.",
    "",
    `Source of truth: ${somaHome}`,
    "",
    "## Use",
    "",
    "- Read `~/.grok/skills/soma/context.md` for the full projected assistant context.",
    "- Read `~/.grok/skills/soma/memory-layout.md` before using persistent memory.",
    "- Read `~/.grok/skills/soma/skills.md` for the declared Soma skills.",
    "- Read `~/.grok/skills/soma/policy.md` for the substrate policy projection.",
    "- Read `~/.grok/skills/soma/active-isa.md` for the active ISA verification contract when that file is present.",
    "- Use the `the-algorithm` skill when work should run through Soma Algorithm mode.",
    "- Treat project-local `.grok/rules/soma/` context as an overlay on this home projection.",
    "- Do not assume a global `soma` binary exists; run `bun run soma ...` from the Soma repo.",
    "",
    "This projection is generated from Soma. Author changes in the Soma home and rerun `soma install grok --apply`.",
    "",
    "## Current Projection",
    "",
    renderAssistantCore(input),
  ].join("\n");
}

function renderGrokRulesReadme(): string {
  return [
    "# Soma Grok Projection",
    "",
    "This directory is generated by Soma. The portable source of truth is the Soma home.",
    "",
    "Grok auto-discovers project rules under `.grok/rules/` (walked from the working directory to the repo root, regardless of project trust), so this overlay loads as project context. It is context-only by design: hooks and policy are installed at user scope (`~/.grok/`), never from a repo.",
    "",
    "## Files",
    "",
    "- `context.md` — assistant identity, principal, telos, and operating rules",
    "- `memory-layout.md` — pointers into the Soma memory tree",
    "- `skills.md` — discovered Soma skills",
    "- `policy.md` — substrate policy projection",
    "",
    "Do not edit these files by hand; rerun `soma install grok --apply` after changing Soma source context.",
  ].join("\n");
}

/**
 * Workspace projection (`soma project grok` / project overlays). Files
 * land under `<repo>/.grok/rules/soma/`, the project-scoped rules dir
 * Grok auto-discovers regardless of trust (KTD-4a) — unlike the home
 * `~/.grok/rules/` dir, which Grok never loads. Context-only: no hooks
 * or policy assets ever ship at project scope (KTD-4).
 */
export function projectGrok(input: ProjectionInput): Projection {
  const instructions = renderInstructions(input);

  return {
    substrate: "grok",
    instructions,
    files: [
      { path: ".grok/rules/soma/README.md", content: renderGrokRulesReadme() },
      { path: ".grok/rules/soma/context.md", content: instructions },
      { path: ".grok/rules/soma/memory-layout.md", content: renderMemoryLayout(input) },
      { path: ".grok/rules/soma/skills.md", content: renderSkills(input) },
      { path: ".grok/rules/soma/policy.md", content: renderGrokPolicy() },
    ],
  };
}

/**
 * Home projection (`soma install grok`). Files are relative to the Grok
 * home (`~/.grok`) and route through the two verified auto-loaded
 * discovery surfaces (KTD-4a): the `skills/soma/` entry skill rendered
 * here, and the `AGENTS.md` pointer block patched post-projection by
 * `configureGrokAgentsPointer`.
 */
export function projectGrokHome(input: ProjectionInput, somaHome: string): Projection {
  const instructions = renderInstructions(input);
  // Portable Soma skills project through the default substrate rewrite
  // (Claude memory roots -> Soma memory, Claude-only lines stripped) —
  // grok deliberately takes the default-rewrite branch, same as codex.
  const portableSkillFiles = input.profile.skills.flatMap((skill) =>
    (skill.files ?? []).map((file) => ({
      path: `skills/${skill.name}/${file.path}`,
      content: rewriteSubstrateProjectionContent({
        substrate: "grok",
        path: file.path,
        content: file.content,
      }),
    })),
  );

  return {
    substrate: "grok",
    instructions,
    files: [
      { path: "skills/soma/SKILL.md", content: renderGrokHomeSkill(input, somaHome) },
      { path: "skills/soma/context.md", content: instructions },
      { path: "skills/soma/memory-layout.md", content: renderMemoryLayout(input) },
      { path: "skills/soma/skills.md", content: renderSkills(input) },
      { path: "skills/soma/policy.md", content: renderGrokPolicy() },
      ...portableSkillFiles,
      // After the portable skills on purpose: when `the-algorithm` is
      // imported as a portable skill, the static rendering contract
      // overwrites its SKILL.md while Workflows/references ship through
      // (same ordering contract as projectCodexHome).
      { path: "skills/the-algorithm/SKILL.md", content: renderAlgorithmRenderingContract("Grok") },
      // Active-ISA projection (#37). OMITTED when no active ISA — AC-2.
      ...activeIsaBundleFile("grok", input.activeIsa),
    ],
  };
}

export const grokAdapter: SomaAdapter = {
  name: "grok",
  detect() {
    return Promise.resolve(existsSync(grokHomeDir()));
  },
  project(input) {
    return Promise.resolve(projectGrok(input));
  },
  run(task: SomaTask) {
    return Promise.resolve({
      taskId: task.id,
      substrate: "grok",
      status: "failed",
      summary: "Grok execution is not implemented yet; use project() to generate the substrate bundle.",
    });
  },
};
